// Generated by gencpp from file elevation_map_msgs/InitializeResponse.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_INITIALIZERESPONSE_H
#define ELEVATION_MAP_MSGS_MESSAGE_INITIALIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace elevation_map_msgs
{
template <class ContainerAllocator>
struct InitializeResponse_
{
  typedef InitializeResponse_<ContainerAllocator> Type;

  InitializeResponse_()
    : success(false)  {
    }
  InitializeResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InitializeResponse_

typedef ::elevation_map_msgs::InitializeResponse_<std::allocator<void> > InitializeResponse;

typedef boost::shared_ptr< ::elevation_map_msgs::InitializeResponse > InitializeResponsePtr;
typedef boost::shared_ptr< ::elevation_map_msgs::InitializeResponse const> InitializeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elevation_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elevation_map_msgs/InitializeResponse";
  }

  static const char* value(const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elevation_map_msgs::InitializeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elevation_map_msgs::InitializeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_INITIALIZERESPONSE_H
