// Generated by gencpp from file elevation_map_msgs/Statistics.msg
// DO NOT EDIT!


#ifndef ELEVATION_MAP_MSGS_MESSAGE_STATISTICS_H
#define ELEVATION_MAP_MSGS_MESSAGE_STATISTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace elevation_map_msgs
{
template <class ContainerAllocator>
struct Statistics_
{
  typedef Statistics_<ContainerAllocator> Type;

  Statistics_()
    : header()
    , pointcloud_process_fps(0.0)  {
    }
  Statistics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pointcloud_process_fps(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pointcloud_process_fps_type;
  _pointcloud_process_fps_type pointcloud_process_fps;





  typedef boost::shared_ptr< ::elevation_map_msgs::Statistics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elevation_map_msgs::Statistics_<ContainerAllocator> const> ConstPtr;

}; // struct Statistics_

typedef ::elevation_map_msgs::Statistics_<std::allocator<void> > Statistics;

typedef boost::shared_ptr< ::elevation_map_msgs::Statistics > StatisticsPtr;
typedef boost::shared_ptr< ::elevation_map_msgs::Statistics const> StatisticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elevation_map_msgs::Statistics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elevation_map_msgs::Statistics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::elevation_map_msgs::Statistics_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::Statistics_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pointcloud_process_fps == rhs.pointcloud_process_fps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::elevation_map_msgs::Statistics_<ContainerAllocator1> & lhs, const ::elevation_map_msgs::Statistics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace elevation_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elevation_map_msgs::Statistics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elevation_map_msgs::Statistics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elevation_map_msgs::Statistics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "862e05f7b2e4eec3255cdbf6fad6ee44";
  }

  static const char* value(const ::elevation_map_msgs::Statistics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x862e05f7b2e4eec3ULL;
  static const uint64_t static_value2 = 0x255cdbf6fad6ee44ULL;
};

template<class ContainerAllocator>
struct DataType< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elevation_map_msgs/Statistics";
  }

  static const char* value(const ::elevation_map_msgs::Statistics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 pointcloud_process_fps\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::elevation_map_msgs::Statistics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pointcloud_process_fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Statistics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elevation_map_msgs::Statistics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::elevation_map_msgs::Statistics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pointcloud_process_fps: ";
    Printer<double>::stream(s, indent + "  ", v.pointcloud_process_fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELEVATION_MAP_MSGS_MESSAGE_STATISTICS_H
